version: '3.8'

services:
  fastapi_service:
    build: .
    container_name: fastapi_container
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    restart: always